# Pipeline variables
variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml -Dmaven.repo.local=.m2/repository --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

# Cache policy - Share target folders between jobs - Note that key is related to a commit and is purged automatically after pipeline execution
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - $CI_PROJECT_DIR/.m2/repository/**/*
    - $CI_PROJECT_DIR/**/target/**/*

default:
  image: maven:3.6.0-jdk-11
  before_script:
    - apt update && apt install -y gettext-base
    - envsubst '${MVN_GROUP} ${MVN_RELEASE} ${MVN_SNAPSHOTS}' < pom.xml > pom.subst && mv -f pom.subst pom.xml

# Stages definition
stages:
  - build
  - test
  - deploy

# Build job with maven plugin execution policies define in parent pom
tabou2:build:
  script:
    - sh ./mvnw $MAVEN_CLI_OPTS -U clean package
  stage: build
  except:
    refs:
      - master
      - open/master 
  artifacts:
    paths:
      - $CI_PROJECT_DIR/tabou2-facade/target/tabou2-facade-*.jar
      - $CI_PROJECT_DIR/tabou2-facade/target/tabou2-facade-*.war
      - $CI_PROJECT_DIR/tabou2-facade/target/tabou2.war

tabou2:build:master:
  script:
    - sh ./mvnw $MAVEN_CLI_OPTS -U clean package -DskipTests
  stage: build  
  only:
    refs:
      - master
      - open/master   
  artifacts:
    paths:
      - $CI_PROJECT_DIR/tabou2-facade/target/tabou2-facade-*.jar
      - $CI_PROJECT_DIR/tabou2-facade/target/tabou2-facade-*.war   
      - $CI_PROJECT_DIR/tabou2-facade/target/tabou2.war

# Sonar code quality analysis - note a full test coverage report through a jacoco.exec merged file in base project folder
tabou2:sonar:
  stage: test
  dependencies:
    - tabou2:build
  except:
    refs:
      - master
      - open/master
  allow_failure: true
  script:
    - >
      sh ./mvnw $MAVEN_CLI_OPTS -U compile sonar:sonar
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
      -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
      -Dsonar.gitlab.project_id=$CI_PROJECT_ID
      -Dsonar.branch.name=$CI_COMMIT_REF_NAME
            

# On master, do not use branch parameter
tabou2:sonar:master:
  stage: test
  dependencies:
    - tabou2:build 
  only:
    refs:
      - open/master
  allow_failure: true
  script:
    - >
      sh ./mvnw $MAVEN_CLI_OPTS -U compile sonar:sonar
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
      -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
      -Dsonar.gitlab.project_id=$CI_PROJECT_ID

.tabou2:deploy:
  stage: deploy
  tags:
    - iaas
  image: glregistry.boost.open.global/boost/docker/mvn-node-jdk11-ansible:latest
  dependencies:
    - tabou2:build  
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$ansible_private_key" | base64 -d)       
  script:
    - cp -f $CI_PROJECT_DIR/tabou2-facade/target/tabou2-facade-*.war $CI_PROJECT_DIR/ansible/dockerize/files/tabou2-facade.war 
    - cd $CI_PROJECT_DIR/ansible  
    - cp tabou2_dev_var.yml $HOME/tabou2_var.yml
    - ansible-playbook tabou2-docker.yml -v -i "${TARGET_ENV}," -u root --ssh-common-args=-oStrictHostKeyChecking=no


tabou2:deploy:
  extends: .tabou2:deploy
  only:
    refs:
      - open/develop
  variables: 
    TARGET_ENV: REN1VML0096
    
tabou2:deploy:master:
  extends: .tabou2:deploy
  only:
    refs:
      - open/master
  variables: 
    TARGET_ENV: REN1VML0095