create table if not exists ddc.pc_ddc (
    id bigint generated by default as identity,
    completude_dossier timestamp,
    decision_dossier varchar(255),
    depot_dossier timestamp,
    num_pc varchar(255),
    surf_autre float,
    surf_bureaux float,
    surf_commerces float,
    surf_equip_pub float,
    surf_industries float,
    primary key (id)
);
