
-- Création du schéma DDC -- temporaire
CREATE SCHEMA ddc;

-- Création de la table des permis de construire : nécessaire seulement pour environnement de dev et intégration continue

create table ddc.pc_ddc (
    id int8 generated by default as identity,
    completude_dossier timestamp,
    decision_dossier varchar(255),
    depot_dossier timestamp,
    num_pc varchar(255),
    surf_autre float8,
    surf_bureaux float8,
    surf_commerces float8,
    surf_equip_pub float8,
    surf_industries float8,
    primary key (id)
)