--------------------------------------------------------------------------
--
-- Creation des tables de la base de données de l'application
--
--------------------------------------------------------------------------


-- Scripts de création de la BDD

create table agapeo (
                        id bigint generated by default as identity,
                        annee_agre_etat varchar(255),
                        libelle varchar(255),
                        logements_access_sociale integer,
                        logements_locat_regul integer,
                        logements_locat_social integer,
                        logements_maitrise integer,
                        logements_pls integer,
                        num_pc varchar(255),
                        plh_logements_livres bigint,
                        plh_logements_prevus bigint,
                        primary key (id)
);


create table etape_operation (
                                 id bigint generated by default as identity,
                                 libelle varchar(255),
                                 id_operation bigint,
                                 primary key (id)
);


create table etape_programme (
                                 id bigint generated by default as identity,
                                 libelle varchar(255),
                                 id_programme bigint,
                                 id_type_tiers bigint,
                                 primary key (id)
);


create table evenement_operation (
                                     id bigint generated by default as identity,
                                     create_date timestamp,
                                     create_user varchar(255),
                                     description varchar(255),
                                     event_date timestamp,
                                     modif_date timestamp,
                                     modif_user varchar(255),
                                     systeme boolean default false,
                                     id_operation bigint,
                                     id_type_evenement bigint,
                                     primary key (id)
);

create table evenement_programme (
                                     id bigint generated by default as identity,
                                     create_date timestamp,
                                     create_user varchar(255),
                                     description varchar(255),
                                     event_date timestamp,
                                     modif_date timestamp,
                                     modif_user varchar(255),
                                     systeme boolean default false,
                                     id_programme bigint,
                                     id_type_evenement bigint,
                                     primary key (id)
);


create table nature (
                        id bigint generated by default as identity,
                        date_inactif timestamp,
                        libelle varchar(255),
                        primary key (id)
);

create table operation (
                           id bigint generated by default as identity,
                           autorisation_date timestamp,
                           cloture_date timestamp,
                           code varchar(255),
                           create_date timestamp,
                           create_user varchar(255),
                           description varchar(255),
                           diffusion_retreinte boolean,
                           logement_prevu integer,
                           modif_date timestamp,
                           modif_user varchar(255),
                           nom varchar(255),
                           operation varchar(255),
                           operationnel_date timestamp,
                           plhlogement_prevu integer,
                           plhlogement_livre integer,
                           secteur boolean,
                           id_nature bigint,
                           primary key (id)
);


create table operation_tiers (
                                 id bigint generated by default as identity,
                                 create_date timestamp,
                                 create_user varchar(255),
                                 modif_date timestamp,
                                 modif_user varchar(255),
                                 id_operation bigint,
                                 id_tiers bigint,
                                 id_type_tiers bigint,
                                 primary key (id)
);


create table programme (
                           id bigint generated by default as identity,
                           attribution_date timestamp,
                           attribution_fonciere_aAnnee varchar(255),
                           autorisation_date varchar(255),
                           cloture_date timestamp,
                           code varchar(255),
                           commercialisation_date timestamp,
                           create_date timestamp,
                           create_user varchar(255),
                           demarrage_date timestamp,
                           description varchar(255),
                           livraison_date timestamp,
                           logements_access_aide integer,
                           logements_access_libre integer,
                           logements_access_maitrise integer,
                           logements_locat_aide integer,
                           logements_locat_regul integer,
                           logements_pls integer,
                           logements_total integer,
                           modif_date timestamp,
                           modif_user varchar(255),
                           nom varchar(255),
                           programme varchar(255),
                           primary key (id)
);


create table programme_tiers (
                                 id bigint generated by default as identity,
                                 create_date timestamp,
                                 create_user varchar(255),
                                 modif_date timestamp,
                                 modif_user varchar(255),
                                 id_programme bigint,
                                 id_tiers bigint,
                                 id_type_tiers bigint,
                                 primary key (id)
)



create table tiers (
                       id bigint generated by default as identity,
                       adresse_cp varchar(255),
                       adresse_num varchar(255),
                       adresse_rue varchar(255),
                       adresse_ville varchar(255),
                       contact varchar(255),
                       correspondant varchar(255),
                       date_inactif timestamp,
                       email varchar(255),
                       nom varchar(255),
                       site_web varchar(255),
                       telecopie varchar(255),
                       telephone varchar(255),
                       primary key (id)
);


create table type_document (
                               id bigint generated by default as identity,
                               date_inactif timestamp,
                               libelle varchar(255),
                               primary key (id)
);


create table type_evenement (
                                id bigint generated by default as identity,
                                date_inactif timestamp,
                                libelle varchar(255),
                                primary key (id)
);


create table type_tiers (
                            id bigint generated by default as identity,
                            create_date timestamp,
                            create_user varchar(255),
                            date_inactif timestamp,
                            libelle varchar(255),
                            primary key (id)
);


-- Ajout des clés étrangères


alter table if exists etape_operation
    add constraint FKmnfwd0r1gm6ftejbo9woliqfp
        foreign key (id_operation)
            references operation;


alter table if exists etape_programme
    add constraint FKhk7mapt63mfbxdrjcbhg8nxpf
        foreign key (id_programme)
            references programme;


alter table if exists etape_programme
    add constraint FKeqgbdgngapl87iu1htdvomx5a
        foreign key (id_type_tiers)
            references type_tiers;


alter table if exists evenement_operation
    add constraint FKkr4528e5v3lr3054v1d2tds4c
        foreign key (id_operation)
            references operation;


alter table if exists evenement_operation
    add constraint FKcr9ky2twrrxbmle71ploir5g6
        foreign key (id_type_evenement)
            references type_evenement;


alter table if exists evenement_programme
    add constraint FK7sw203ns1mfwaqkccwplsobgu
        foreign key (id_programme)
            references programme;


alter table if exists evenement_programme
    add constraint FKgnmrutcu969nk0arjsh73i212
        foreign key (id_type_evenement)
            references type_evenement;


alter table if exists operation
    add constraint FKrwdfcmejegpwofrh8suxs9xw6
        foreign key (id_nature)
            references nature;


alter table if exists operation_tiers
    add constraint FKepwn2h1eghs8imwf4dcplsrpd
        foreign key (id_operation)
            references operation;


alter table if exists operation_tiers
    add constraint FK1eadn10xklcnqh0unfuu411ba
        foreign key (id_tiers)
            references tiers;


alter table if exists operation_tiers
    add constraint FK7nefer0uwhs3fsi06b97a4yln
        foreign key (id_type_tiers)
            references type_tiers;


alter table if exists programme_tiers
    add constraint FKmhp8mixi41itd1rxx331uahtu
        foreign key (id_programme)
            references programme;


alter table if exists programme_tiers
    add constraint FKgkfw9jyg12hc41tp3udh7h49j
        foreign key (id_tiers)
            references tiers;


alter table if exists programme_tiers
    add constraint FKo2rxjnajre6agek7wlpfw3hfn
        foreign key (id_type_tiers)
            references type_tiers;
