
-- Création du schéma DDC -- temporaire
CREATE SCHEMA ddc;
CREATE SCHEMA limite_admin;

-- Création de la table des permis de construire : nécessaire seulement pour environnement de dev et intégration continue

create table ddc.pc_ddc (
    id bigint generated by default as identity,
    completude_dossier timestamp,
    decision_dossier varchar(255),
    depot_dossier timestamp,
    num_pc varchar(255),
    surf_autre float,
    surf_bureaux float,
    surf_commerces float,
    surf_equip_pub float,
    surf_industries float,
    primary key (id)
);

-- Scripts temporaire. A revoir pour intégrer les scripts fournis par denis
create table limite_admin.commune (
                                              id bigint not null,
                                              code_insee varchar(255),
                                              nom varchar(255),
                                              primary key (id)
);


create table limite_admin.iris (
                                   id bigint not null,
                                   nom varchar(255),
                                   primary key (id)
);


create table limite_admin.plui (
                                   id bigint not null,
                                   nomQuartier varchar(255),
                                   nuQuartier varchar(255),
                                   primary key (id)
);


create table limite_admin.quartier (
                                       id bigint not null,
                                       nomQuartier varchar(255),
                                       nuQuartier varchar(255),
                                       primary key (id)
);

