--------------------------------------------------------------------------
--
-- Creation des tables de la base de données de l'application
--
--------------------------------------------------------------------------

-- Placer ici les instructions SQL permetttant la création de la base de donnée de l'application


CREATE TABLE etape_operation (id bigint GENERATED BY DEFAULT AS IDENTITY,
                              libelle varchar(255),
                              id_operation bigint, PRIMARY KEY (id));

CREATE TABLE etape_programme (id bigint GENERATED BY DEFAULT AS IDENTITY,
                              libelle varchar(255),
                              id_programme bigint, id_type_tiers bigint, PRIMARY KEY (id));

CREATE TABLE evenement (id bigint GENERATED BY DEFAULT AS IDENTITY,
                        create_date TIMESTAMP,
                        create_user varchar(255),
                        description varchar(255),
                        event_date TIMESTAMP,
                        modif_date TIMESTAMP,
                        modif_user varchar(255),
                        systeme boolean, id_operation bigint, id_type_evenement bigint, PRIMARY KEY (id));

CREATE TABLE nature (id bigint GENERATED BY DEFAULT AS IDENTITY,
                     libelle varchar(255),
                     PRIMARY KEY (id));

CREATE TABLE OPERATION (id bigint GENERATED BY DEFAULT AS IDENTITY,
                        autorisation_date TIMESTAMP,
                        cloture_date TIMESTAMP,
                        code varchar(255),
                        create_date TIMESTAMP,
                        create_user varchar(255),
                        description varchar(255),
                        diffusion_retreinte boolean, logement_prevu integer, modif_date TIMESTAMP,
                        modif_user varchar(255),
                        nom varchar(255),
                        OPERATION varchar(255),
                        operationnel_date TIMESTAMP,
                        plhlogement_prevu integer, plhlogement_livre integer, secteur boolean, id_nature bigint, PRIMARY KEY (id));

CREATE TABLE operation_tiers (id bigint GENERATED BY DEFAULT AS IDENTITY,
                              create_date TIMESTAMP,
                              create_user varchar(255),
                              modif_date TIMESTAMP,
                              modif_user varchar(255),
                              id_operation bigint, id_programme bigint, id_tiers bigint, id_type_tiers bigint, PRIMARY KEY (id));

CREATE TABLE programme (id bigint GENERATED BY DEFAULT AS IDENTITY,
                        attribution_date TIMESTAMP,
                        attribution_fonciere_a_annee varchar(255),
                        autorisation_date varchar(255),
                        cloture_date TIMESTAMP,
                        code varchar(255),
                        commercialisation_date TIMESTAMP,
                        create_date TIMESTAMP,
                        create_user varchar(255),
                        demarrage_date TIMESTAMP,
                        description varchar(255),
                        livraison_date TIMESTAMP,
                        logements_access_aide varchar(255),
                        logements_access_libre varchar(255),
                        logements_locat_aide varchar(255),
                        logements_locat_regul varchar(255),
                        logements_maitrise varchar(255),
                        logements_pls varchar(255),
                        logements_total varchar(255),
                        modif_date TIMESTAMP,
                        modif_user varchar(255),
                        nom varchar(255),
                        programme varchar(255),
                        PRIMARY KEY (id));

CREATE TABLE t_authority (id_authority bigint GENERATED BY DEFAULT AS IDENTITY,
                          code varchar(255),
                          PRIMARY KEY (id_authority));

CREATE TABLE t_configuration (id_configuration bigint GENERATED BY DEFAULT AS IDENTITY,
                              COMMENT varchar(255),
                              PRIMARY KEY (id_configuration));

CREATE TABLE t_refresh_token (id_refresh_token bigint GENERATED BY DEFAULT AS IDENTITY,
                              token varchar(255),
                              PRIMARY KEY (id_refresh_token));

CREATE TABLE tiers (id bigint GENERATED BY DEFAULT AS IDENTITY,
                    adresse_cp varchar(255),
                    adresse_num varchar(255),
                    adresse_rue varchar(255),
                    adresse_ville varchar(255),
                    contact varchar(255),
                    correspondant varchar(255),
                    date_inactif TIMESTAMP,
                    email varchar(255),
                    nom varchar(255),
                    site_web varchar(255),
                    telecopie varchar(255),
                    telephone varchar(255),
                    PRIMARY KEY (id));gi

CREATE TABLE type_document (id bigint GENERATED BY DEFAULT AS IDENTITY,
                            libelle varchar(255),
                            PRIMARY KEY (id));

CREATE TABLE type_evenement (id bigint GENERATED BY DEFAULT AS IDENTITY,
                             libelle varchar(255),
                             PRIMARY KEY (id));

CREATE TABLE type_tiers (id bigint GENERATED BY DEFAULT AS IDENTITY,
                         create_date TIMESTAMP,
                         create_user varchar(255),
                         date_inactif TIMESTAMP,
                         libelle varchar(255),
                         PRIMARY KEY (id));


