image:
  tag: open-develop
  env:
    - name: TABOU2_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: tabou2-secret-dev
          key: database.tabou2.password

    - name: DDC_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: tabou2-secret-dev
          key: database.ddc.password

    - name: SIG_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: tabou2-secret-dev
          key: database.sig.password

    - name: DDC_BDD_HOST
      value: georchestra-bdd-qua-georchestra-service-bdd
    - name: TABOU2_BDD_HOST
      value: georchestra-bdd-qua-georchestra-service-bdd
    - name: SIG_BDD_HOST
      value: georchestra-bdd-qua-georchestra-service-bdd

    - name: SWAGGER_SERVER
      value: https://tabou2-back-dev.rennes-metropole-georchestra.karbon.open.global/tabou2