db_host: database
db_name: georchestra
db_user: tabou2
db_password: tabou2
db_port: 5432

db_ddc_host: database
db_ddc_name: georchestra
db_ddc_user: ddc_user
db_ddc_password: ddc_user
db_ddc_port: 5432

db_sig_host: database
db_sig_name: georchestra
db_sig_user: sig_user
db_sig_password: sig_user
db_sig_port: 5432

server_expose_port: 8083

smtp_host: mailhog
smtp_port: 1025
smtp_username:
smtp_password:

ldap_host: ldap
ldap_port: 389
ldap_username: cn=admin,dc=georchestra,dc=org
ldap_password: secret

backend_url: https://georchestra.open-dev.com/tabou2/




