spec:
  template:
    spec:
      containers:
        - name: boost-deploy
          volumeMounts:
            - mountPath: /etc/georchestra
              name: georchestra-config
      volumes:
        - name: georchestra-config
          persistentVolumeClaim:
            claimName: georchestra-config-data-pv-claim-TARGET_ENV
